### ISSUE TITLE
PutObject with object lock

### ISSUE THREAD

**Issue by Xaero** [aws/aws-sdk-php#2256]
Hi, 

I'm trying to upload a file to a AWS S3 which have object lock enabled. Using the CLI it works as expected, however, with the PHP SDK I get the following error:
```
Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters
```

Now I saw that the ApplyChecksumMiddleware could handle this (https://github.com/aws/aws-sdk-php/blob/ff4872f72fac84ce6e384c4f40d30ec7b0d1eeda/src/S3/ApplyChecksumMiddleware.php#L58), but I was curious why checking on 'httpChecksumRequired' is required and this is not always done (f.e. always on the PutObject)

**Comment by SamRemis** [comment]
I'm sorry, I don't understand the question, are you asking why we don't default to always adding the checksum to every operation?  putObject could wind up having a very large payload, which may not be able to fit in memory.  Because of this, s3 doesn't require a checksum on putObject.

The ones that do require it use the httpChecksumRequired flag to let us know when to add a checksum.
This was added with the below pull request about a year ago as a way to not have to hard code which operations require checksums:
https://github.com/aws/aws-sdk-php/commit/601a0007152e0396e518abb5d5865c0c805e72da

Does that answer your question?

**Comment by Xaero** [comment]
Thanks for your reply. I'm not sure how I can upload a big file to an object locked s3 bucket. I tried manually adding the Content-MD5 param, but this resulted in errors:
```
The Content-MD5 you specified did not match what we received.</Message><ExpectedDigest>6sW5nMzK28+aiJKrQ6B7RQ==</ExpectedDigest><CalculatedDigest>/LTptx5/M+5dPiD3fcgnDQ==</CalculatedDigest>
The Content-MD5 you specified did not match what we received.</Message><ExpectedDigest>6sW5nMzK28+aiJKrQ6B7RQ==</ExpectedDigest><CalculatedDigest>VIh4MP7KNdVkn7gpEmgm9A==</CalculatedDigest>
```
However, the digest I'm passing to the 'upload' function, is only once calculated and the SDK splits it later to a multipart upload:
```
     $options['Content-MD5'] = base64_encode(md5($body, true));
     $this->s3Client->upload($this->bucket, $key, $body, $acl, ['params' => $options]);
```
```
array:1 [
  "params" => array:3 [
    "ContentType" => "application/x-zip"
    "ContentLength" => 108063064
    "ContentMD5" => "6sW5nMzK28+aiJKrQ6B7RQ=="
  ]
]
```
It seems that the above code for uploading a small file (1MB versus 100MB) works as expected, but when uploading a large files the digest must be different. 

Is there any other way to include the header at a multipart PutObject command? Or would it be an idea to add a configurable option to include automatically a Content-MD5 hash when required?

**Comment by SamRemis** [comment]
Well that's the exact use case where S3 doesn't require a checksum, so I'm a bit confused about why you're trying to add it- it isn't required.  The upload should work if you just don't try to add the header.  I just double checked and was able to upload a 700 mb file using the code below:
`$client = new S3Client([
    'version' => 'latest',
    'region'  => 'us-east-2',
]);
$resource = Utils::tryFopen('/path/to/file', 'r');
$stream = Utils::streamFor($resource);
$client->upload(
    'example-bucket',
    'large_file',
    $stream
);
`

Are you getting an error if you leave out the ContentMD5 header?

**Comment by Xaero** [comment]
I'm getting the following error:
```
Content-MD5 HTTP header is required for Put Object 
```

That's the reason Im trying to manually add the headers. The bucket does have Object Lock enabled.

**Comment by marvinlinthorst** [comment]
Thanks for the help so far! Nope, it's a fopen resource. The code is called in 'laravel backup', which is based on Laravel together with Flysystem.

```
        $handle = fopen($file, 'r+');
```

https://github.com/spatie/laravel-backup/blob/39dc00988cd28e7cd06237dae27bf463fa9420fd/src/BackupDestination/BackupDestination.php#L82

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L389

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L606

**Comment by Xaero** [comment]
Thanks for the help so far! Nope, it's a fopen resource. The code is called in 'laravel backup', which is based on Laravel together with Flysystem.

```
        $handle = fopen($file, 'r+');
```

https://github.com/spatie/laravel-backup/blob/39dc00988cd28e7cd06237dae27bf463fa9420fd/src/BackupDestination/BackupDestination.php#L82

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L389

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L606

**Comment by SamRemis** [comment]
No matter what I try, I haven't been able to reproduce the issue.  I tried now with and without object lock, as well as with a zip file as it appears you are using.  

I did notice one thing that is odd about your error:
`Content-MD5 HTTP header is required for Put Object `
Does that error change when you're using a larger object?  The default value to use a multipart upload instead of a put object call is 16mb, so I'd think the error would be on 'Upload Part' instead of 'Put Object'

**Comment by Xaero** [comment]
I've now tried updating the SDK to the latest version and trying it without the packages. I'm using the following script:

```
$client = new S3Client([
    'version' => 'latest',
    'region' => 'eu-central-1',
]);
$resource = fopen('file.zip', 'r+');
$stream = Utils::streamFor($resource);

$client->upload('bucket', 'key'.date('YmdHis'), $stream);

```

When I now upload a 400kb zip or a 400mb file I get the following error. Both errors mention 'Error executing "PutObject"'
```
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://bucket.s3.eu-central-1.amazonaws.com/key20210609062846"; AWS HTTP error: Client error: `PUT https://bucket.s3.eu-central-1.amazonaws.com/key20210609062846` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Content-MD5 HTTP header is required fo (truncated...)
 InvalidRequest (client): Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters</Message><RequestId>A857F0XN6PB1SEAJ</RequestId><HostId>xxx</HostId></Error>'
```

**Comment by Xaero** [comment]
@SamRemis Do you maybe have any idea why above happens? Or a workaround to still use the PutObject command?

**Comment by SamRemis** [comment]
@Xaero Can you tell me what version of the SDK you're using?  That looks like it may be an issue that was fixed more recently.

**Comment by Xaero** [comment]
@SamRemis Just updated to the latest SDK (3.185.18), but still having the same error. 
'Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters'

**Comment by Xaero** [comment]
This issue is still not resolved

**Comment by stobrien89** [comment]
Hi @Xaero,

Apologies for the delay.  I was able to reproduce. Looks like this is occurring with all `PUT` operations that specify a `[httpChecksum]['requestChecksumRequired]` value of false when making requests to buckets with object-lock enabled. One option would be for us to introduce an `objectLock` flag to ignore that value, but we're definitely open to other suggestions.

**Comment by stobrien89** [comment]
Hi @Xaero,

Thanks again for your patience and thanks again for reporting this to us.  

We've just added the `AddContentMD5` parameter to `PutObject` and `UploadPart`, which when set to `true` will automatically calculate the md5 checksum for you (adding the header to the request). 

For customizations like the ObjectUploader, MultipartUploader and Transfer utility, all you'll need to do is pass `'add_content_md5' => true` to the options at instantiation.

Drawing from one of your examples above, this is what it would look like: 

```
$this->s3Client->upload($this->bucket, $key, $body, $acl, ['params' => $options, 'add_content_md5' => true]);
```

This feature will be available in tomorrow's release.  Let us know if you have any additional questions!
