### ISSUE TITLE
Shared config files still checked despite "use_aws_shared_config_files" = false

### ISSUE THREAD

**Issue by markinjapan** [aws/aws-sdk-php#3026]
### Describe the bug

The `use_aws_shared_config_files` config setting is not respected when resolving the following client configuration options:
* `region`
* `sigv4a_signing_region_set`

This causes the `ConfigurationResolver::resolve()` function to check for `~/.aws/config` files unnecessarily.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

By setting the `use_aws_shared_config_files` config option, when all other config options are resolved, the shared config files should never be checked.

### Current Behavior

Currently shared config files are checked for `region` and `sigv4a_signing_region_set`.

### Reproduction Steps

```php
// Create S3 client
$s3_client = new Aws\S3\S3Client([
    'region' => 'ap-northeast-1',
    'credentials' => new Aws\Credentials\Credentials(
        'MYAWSKEY',
        'xxxxxxxxxxxxxxxx'
    ),
    'version' => '2006-03-01',
    'use_aws_shared_config_files' => false,
]);
```

### Possible Solution

In the methods `ClientResolver::_default_sigv4a_signing_region_set()` and `ClientResolver::_default_region()`, the `$args` argument is not being passed to the `ConfigurationResolver::resolve()` method.

This means the config option `use_aws_shared_config_files` is not respected.

### SDK version used

3.326.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.13, MacOS 15.1 (24B83)

**Comment by yenfryherrerafeliz** [comment]
Hi @markinjapan, thanks for reporting this. I have opened a [PR](https://github.com/aws/aws-sdk-php/pull/3027) to address this issue.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @markinjapan, the reported issue here should be fixed now. 

I will close this issue but please feel free to reach out if you need anything else that we can help with.

Thank you!

**Comment by the6thBook** [comment]
Still getting AWS-3.356.42_PHAR

[Tue Oct 28 19:46:09.990728 2025] [php:warn] [pid 10988:tid 10988] [client X.X.X.X:0] PHP Warning:  file_get_contents(/.aws/credentials): Failed to open stream: Permission denied in phar:///XXX/aws.phar/Aws/functions.php on line 409
[Tue Oct 28 19:46:09.990807 2025] [php:warn] [pid 10988:tid 10988] [client X.X.X.X:0] PHP Warning:  file_get_contents(/.aws/config): Failed to open stream: Permission denied in phar:///XXX/aws.phar/Aws/functions.php on line 409
