### ISSUE TITLE
aws kinesis put recrord throws exceptin

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php#650]
here's the php code snippet

```php
...
$result = $client->putRecords(array(
    // Records is required
    'Records' => array(
        array(
            // Data is required
            'Data' => 'string',
            'ExplicitHashKey' => 'string',
            // PartitionKey is required
            'PartitionKey' => 'string',
        ),
        // ... repeated
    ),
    // StreamName is required
    'StreamName' => 'string',
));
...
```

and the exception being returned
```log

Fatal error: Uncaught exception 'Aws\Kinesis\Exception\KinesisException' with message 'Error executing "PutRecords" on "https://kinesis.us-east-1.amazonaws.com"; AWS HTTP error: Client error: 400 SerializationException (client): 'string' can not be converted to a Blob: Base64 encoded length is expected a multiple of 4 bytes but found: 6 - {"__type":"SerializationException","Message":"'string' can not be converted to a Blob: Base64 encoded length is expected a multiple of 4 bytes but found: 6"}'
...

Process finished with exit code 255
```

**Comment by jeremeamia** [comment]
What version of the SDK are you using?

**Comment by BardiaAfshin** [comment]
Tested on 3.0 and 2.8




Same problem



—

**Comment by jeremeamia** [comment]
What patch version of 2.8? We'll investigate this issue.

**Comment by BardiaAfshin** [comment]
here's a copy of my composer.json (originally I was using the aws-sdk-php version 3.0)

```json
{
    "name": "bafshin/php-kinesis",
    "require": {
        "aws/aws-sdk-php": "^2.0"
    },
    "authors": [
        {
            "name": "me",
            "email": "me@me.com"
        }
    ],
    "prefer-stable": true
}
```

composer update (just ran it)

```json
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing guzzlehttp/guzzle (6.0.1)
  - Removing guzzlehttp/psr7 (1.1.0)
  - Removing psr/http-message (1.0)
  - Removing guzzlehttp/promises (1.0.1)
  - Removing mtdowling/jmespath.php (2.2.0)
  - Installing symfony/event-dispatcher (v2.7.1)
    Loading from cache

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Removing aws/aws-sdk-php (2.8.11)
  - Installing aws/aws-sdk-php (2.8.12)
    Downloading: 100%

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
Writing lock file
Generating autoload files
```

BUT WAIT, I just re ran my little snippet of code, and now I'm getting Resource not found exception
```log
Fatal error: Uncaught Aws\Kinesis\Exception\ResourceNotFoundException: AWS Error Code: ResourceNotFoundException, Status Code: 400, AWS Request ID: 4ba4e619-1ac7-11e5-b5ab-5dc35cf881ac, AWS Error Type: client, AWS Error Message: Stream string under account 173213834434 not found., User-Agent: aws-sdk-php2/2.8.11 Guzzle/3.9.3 curl/7.37.1 PHP/5.5.20
```

**Comment by BardiaAfshin** [comment]
Any discoveries on this? The exception is rather vague, and the place it falls in the code, it's not immediately apparent on what the problem is.

**Comment by BardiaAfshin** [comment]
just re-pinging this issue. @jeremeamia

**Comment by jeremeamia** [comment]
@BardiaAfshin, my co-worker, @jeskew, will be addressing you questions soon.

**Comment by jeskew** [comment]
Hi @BardiaAfshin,

Thanks for reporting this. Non-string members of lists were not being properly serialized in JSON payloads, and this was addressed in #658. 

By the way, it looks like you were trying to send the basic formatting example from our documentation, which is just meant to show what format input should take and is not likely to work as is. The second error you encountered is related to this -- the request you sent tried to add an entry to a stream named `string`, which does not exist on your account. You can find more information on how to get started with Kinesis on [the AWS documentation site](http://docs.aws.amazon.com/kinesis/latest/dev/introduction.html).

**Comment by jeskew** [comment]
Closing, as the relevant pull request has been merged into master. Please feel free to reopen if you have any questions.

**Comment by BardiaAfshin** [comment]
Is this latest changes merged to stable branch? I'm still getting this excpetion

here's a snippet of my compser.json

```json
{
    "name": "bardionios/php-kinesis",
    "require": {
        "aws/aws-sdk-php": "^3.0"
    },
    "authors": [
        {
            "name": "bardionios",
            "email": "b@example.com"
        }
    ],
    "prefer-stable": true,
    "minimum-stability": "stable"
}
```

**Comment by jeskew** [comment]
Hi Bardia,

The fix has not yet been included in a stable release. If you'd like to try it out before the next release, you can temporarily change your composer file to require `dev-master` instead of a stable version.

**Comment by BardiaAfshin** [comment]
tested, works.
